name: CD Pipeline

run-name: New Deployment on ${{ inputs.TEST }} | ${{ inputs.IMAGE }}

on:
  workflow_dispatch:
    inputs:
      ECRURL:
        description: "ECR Registry URL (with / at end)"
        required: true
        default: "081654307023.dkr.ecr.ap-south-1.amazonaws.com/"

      REPO:
        description: "Repository Name"
        required: true
        default: "wezvatechpayment"

      IMAGE:
        description: "Image Tag"
        required: true

      TEST:
        description: "Environment"
        required: true
        type: choice
        options:
          - integration
          - regression
          - uat
          - release
